#!/usr/bin/env bash
# Regenerates THIRD_PARTY_LICENSES.md from the current dependency tree.
# Run this whenever go.mod or web/package.json changes.
#
# Requirements:
#   Go toolchain  (go list, go mod download)
#   Node/npm      (npx license-checker)

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/THIRD_PARTY_LICENSES.md"
GOMODCACHE="$(go env GOMODCACHE)"

license_file() {
  local dir="$1"
  find "$dir" -maxdepth 1 \( \
    -name "LICENSE" -o -name "LICENSE.md" -o -name "LICENSE.txt" \
    -o -name "LICENSE.MIT" -o -name "COPYING" \
  \) 2>/dev/null | head -1
}

go_dep_block() {
  local mod="$1" ver="$2"
  local dir="$GOMODCACHE/$mod@$ver"
  local f
  f=$(license_file "$dir") || true

  if [ -z "$f" ]; then
    echo "<!-- WARNING: no license file found for $mod@$ver -->"
    return 0
  fi
  printf '### `%s` %s\n\n' "$mod" "$ver"
  echo '```'
  cat "$f"
  echo '```'
  echo ""
}

# Download any missing modules before scanning
go mod download 2>/dev/null || true

# ── header ─────────────────────────────────────────────────────────────────────

cat > "$OUT" <<'HEADER'
# Third-Party Licenses

SomnaTrace incorporates third-party software. Their licenses and copyright
notices are reproduced below as required by the respective license terms.

This file is auto-generated by `scripts/generate-notices.sh`. Re-run it
whenever `go.mod` or `web/package.json` changes.

---

## Go Dependencies

HEADER

# ── Go deps ────────────────────────────────────────────────────────────────────

while IFS=' ' read -r mod ver; do
  [ "$mod" = "github.com/somnatrace/somnatrace" ] && continue
  [ -z "${ver:-}" ] && continue
  go_dep_block "$mod" "$ver" >> "$OUT" || true
done < <(awk '!/\/go\.mod / {print $1, $2}' "$ROOT/go.sum" | sort -u)

# ── JS deps ────────────────────────────────────────────────────────────────────

cat >> "$OUT" <<'SECTION'
---

## JavaScript / Frontend Dependencies

The following packages are bundled into the SomnaTrace frontend. Only
production runtime dependencies are listed; build-time-only tools
(TypeScript compiler, Vite, PostCSS, etc.) are excluded because they
are not distributed in the binary.

SECTION

_tmpjson=$(mktemp)
cd "$ROOT/web"
npx --yes license-checker \
  --production \
  --excludePackages "somnatrace-ui" \
  --json > "$_tmpjson" 2>/dev/null || true

python3 - "$_tmpjson" >> "$OUT" <<'PY'
import sys, json

with open(sys.argv[1]) as f:
    data = json.load(f)

for name in sorted(data.keys(), key=str.lower):
    info = data[name]
    lic  = info.get('licenses', '')
    repo = info.get('repository', '')
    path = info.get('licenseFile', '')

    print(f"### `{name}`\n")
    print(f"License: {lic}")
    if repo:
        print(f"Repository: {repo}")
    print("")

    basename = path.split('/')[-1].lower() if path else ''
    is_license_file = any(w in basename for w in ('license', 'licence', 'copying', 'notice'))
    if path and is_license_file:
        try:
            with open(path) as lf:
                text = lf.read().strip()
            print("```")
            print(text)
            print("```")
        except OSError:
            print("*(license file not readable)*")
    elif path:
        print(f"*(see {basename} in package source for license terms)*")
    print("")
PY
rm -f "$_tmpjson"

echo "→ Written to $OUT"
